export const officialNames: Record<string, string> = {
  erp: "Enterprise Resource Planning",
  mes: "Manufacturing Execution System",
  mom: "Manufacturing Operations Management",
  plm: "Product Lifecycle Management",
  qms: "Quality Management System",
  scada: "Supervisory Control and Data Acquisition",
  plc: "Programmable Logic Controller",
  dcs: "Distributed Control System",
  ot: "Operational Technology",
  it: "Information Technology",
  cmms: "Computerized Maintenance Management System",
  eam: "Enterprise Asset Management",
  wms: "Warehouse Management System",
  aps: "Advanced Planning and Scheduling",
  scm: "Supply Chain Management",
  iiot: "Industrial Internet of Things",
  poc: "Proof of Concept",
  "it-dx": "Information Technology / Digital Transformation",
};
